# If not specified, bookmarks will use the file 'bookmarks.json'
bookmarks: bookmarks.json
# Keep a local copy of the article in XDG_DATA_HOME
store_articles: true
# If specified, will use chromium to fetch html conntent otherwise  will rely
# on a non-javascript client.
chromium:
  enabled: true
  # If not specified, bookmarks will rely on the environment
  # path: /snap/bin/chromium
